###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother McCracken, CS165
# Author:
#     Edgar Wright
# Summary:
#     This code will take a information about a product and 
#	return it in various forms. It also calculates shipping 
#	and tax
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

